# Generated by Django 4.2.8 on 2023-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono_site', '0002_remove_userprofile_username_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
