# Generated by Django 4.2.8 on 2023-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono_site', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='qqq', max_length=100),
        ),
    ]
