# Generated by Django 4.2.8 on 2023-12-19 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mono_site', '0010_remove_choice_voters_choice_voter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='voter',
        ),
        migrations.AddField(
            model_name='choice',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
