# Generated by Django 4.2.8 on 2023-12-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono_site', '0011_remove_choice_voter_choice_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
